apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    app: frontend
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
