apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-green
  namespace: prod
  labels:
    app: order-service
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
      version: green
  template:
    metadata:
      labels:
        app: order-service
        version: green
    spec:
      containers:
        - name: order-service
          image: 949882743811.dkr.ecr.us-east-1.amazonaws.com/order-service:ga-v1.0.0
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: ecommerce-db.cu7l9seahjyg.us-east-1.rds.amazonaws.com
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: password
