apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: prod
spec:
  selector:
    app: order-service
    version: blue  # change to green for traffic switch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
