apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: prod
spec:
  selector:
    app: product-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
