apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-green
  namespace: prod
  labels:
    app: user-service
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: green
  template:
    metadata:
      labels:
        app: user-service
        version: green
    spec:
      containers:
      - name: user-service
        image: 949882743811.dkr.ecr.us-east-1.amazonaws.com/user-service:ga-v1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: ecommerce-db.cu7l9seahjyg.us-east-1.rds.amazonaws.com
        - name: DB_NAME
          value: users
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: password
