apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: prod
spec:
  selector:
    app: user-service
    version: green  # Initially route to green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
