apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 949882743811.dkr.ecr.us-east-1.amazonaws.com/frontend:qa-v1
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: qa
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
