apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 949882743811.dkr.ecr.us-east-1.amazonaws.com/order-service:qa-v1
        ports:
        - containerPort: 3003
        env:
        - name: DB_HOST
          value: "ecommerce-db.cu7l9seahjyg.us-east-1.rds.amazonaws.com"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: qa
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
