apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 949882743811.dkr.ecr.us-east-1.amazonaws.com/user-service:qa-v1
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "ecommerce-db.cu7l9seahjyg.us-east-1.rds.amazonaws.com"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: password
      volumes:
      - name: db-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: qa
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
